service: dev-app-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

functions:
  developers:
    handler: handler.app
    events:
      - http:
          method: get
          path: developers
          cors: true
      - http:
          method: put
          path: developers/{id}
          cors: true
      - http:
          method: post
          path: newDeveloper
          cors: true
      - http:
          method: delete
          path: developers/{id}
          cors: true
